package com.flipmart.schema.types

import com.beyondeye.graphkool.listOfObjs
import com.beyondeye.graphkool.not
import graphql.Scalars.GraphQLFloat
import graphql.Scalars.GraphQLString
import graphql.schema.GraphQLInputObjectField
import graphql.schema.GraphQLInputObjectType

val orderInputType: GraphQLInputObjectType =
        GraphQLInputObjectType.newInputObject()
                .name("orderInput")
                .description("Order input type")
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("id")
                        .type(GraphQLString)
                        .description("The id of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("customerId")
                        .type(!GraphQLString)
                        .description("The customerId of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("orderStatus")
                        .type(orderStatusType)
                        .description("The orderStatus of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("shippingStatus")
                        .type(shippingStatusType)
                        .description("The shippingStatus of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("productIds")
                        .type(!listOfObjs(GraphQLString))
                        .description("The product ids in the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("discounts")
                        .type(GraphQLFloat)
                        .description("The discounts of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("billingAddress")
                        .type(GraphQLString)
                        .description("The billingAddress of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("shippingAddress")
                        .type(GraphQLString)
                        .description("The shippingAddress of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("mobile")
                        .type(GraphQLString)
                        .description("The mobile of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("email")
                        .type(GraphQLString)
                        .description("The email of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("comments")
                        .type(GraphQLString)
                        .description("The comments of the order"))
                .field(GraphQLInputObjectField.newInputObjectField()
                        .name("tags")
                        .type(listOfObjs(GraphQLString))
                        .description("The tags of the order"))
                .build()
